<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <!--   <link rel="stylesheet" href="./devops.css" > -->

    <title>DevOps</title>
</head>
<script>
// Taken from JFiddle website
function getTime() {
  
  const d =  Date.now();

  const now = new Date();
  const hours = now.getHours();
  const minutes = now.getMinutes();
  const seconds = now.getSeconds();
  return "It's Money Time!  " + hours + ":" + minutes + ":" + seconds;

}

function hello(){

    alert( getTime() );
}

function setButtonTime(){
    var x=document.getElementById("mybutton");
    x.innerHTML="Click for the Time";
    x.innerHTML += getTime();

}

</script>
<body onload="setButtonTime()">


<div>
<center><h3>Sample Javascript on onclick button</h3> </center>
<button class="btn btn-danger" id="mybutton" onclick="hello()">
      ---- no TEXT needed ---
</button>

    <center><h3>Bootstrap alert colors</h3> </center>

</div>
<div class="alert alert-primary" role="alert">
  A simple primary alert—check it out!
</div>
<div class="alert alert-secondary" role="alert">
  A simple secondary alert—check it out!
</div>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
<div class="alert alert-danger" role="alert">
  A simple danger alert—check it out!
</div>
<div class="alert alert-warning" role="alert">
  A simple warning alert—check it out!
</div>
<div class="alert alert-info" role="alert">
  A simple info alert—check it out!
</div>
<div class="alert alert-light" role="alert">
  A simple light alert—check it out!
</div>
<div class="alert alert-dark" role="alert">
  A simple dark alert—check it out!
</div>

</body>
</html>