
FROM nginx

COPY index.html /usr/share/nginx/html/index.html
COPY about.html /usr/share/nginx/html/about.html
COPY styles/styles.css /usr/share/nginx/html/styles/styles.css
COPY images /usr/share/nginx/html/images